version: '3.9'

services:
  db:
    image: postgres:16
    container_name: desi_panel_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: desi
      POSTGRES_PASSWORD: desi
      POSTGRES_DB: desipanel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
